ignore:
  - vulnerability: CVE-2026-54369
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-54370
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-54371
    package:
      name: libattr1
      type: deb
  - vulnerability: CVE-2026-41992
    package:
      name: gzip
      type: deb
